/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
"use strict";

systemDictionary = {
	"carrier_climate_control adapter settings": {
		"en": "Adapter settings for carrier_climate_control",
		"de": "Adaptereinstellungen für carrier_climate_control",
		"ru": "Настройки адаптера для carrier_climate_control",
		"pt": "Configurações do adaptador para carrier_climate_control",
		"nl": "Adapterinstellingen voor carrier_climate_control",
		"fr": "Paramètres d'adaptateur pour carrier_climate_control",
		"it": "Impostazioni dell'adattatore per carrier_climate_control",
		"es": "Ajustes del adaptador para carrier_climate_control",
		"pl": "Ustawienia adaptera dla carrier_climate_control",
		"zh-cn": "carrier_climate_control的适配器设置"
	},
	"option1": {
		"en": "option1",
		"de": "Option 1",
		"ru": "Опция 1",
		"pt": "Opção 1",
		"nl": "Optie 1",
		"fr": "Option 1",
		"it": "opzione 1",
		"es": "Opción 1",
		"pl": "opcja 1",
		"zh-cn": "选项1"
	},
	"option2": {
		"en": "option2",
		"de": "Option 2",
		"ru": "вариант 2",
		"pt": "opção 2",
		"nl": "Optie 2",
		"fr": "Option 2",
		"it": "opzione 2",
		"es": "opcion 2",
		"pl": "Opcja 2",
		"zh-cn": "选项2"
	}
};